spring:
  profiles:
    group:
      "local" : "local, secret"
    active : local
---
server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      encoding: UTF-8
  jpa:
    properties:
      hibernate:
        search:
          backend:
            type: elasticsearch
            elasticsearch:
              version_check:
                enabled: false
            hosts:
              - http://localhost:9200
        format_sql: true
        show_sql: true